bug #PSBM-71332 aka AttributeError: 'NoneType' object has no attribute 'id'
snapshot xml schema changed. anyName elements are there now. we didn't
handle them before. it's time to start. let's grab the node because
there is no structure in the schema. we have nothing to parse here.